import { browser } from '$app/environment';
import { orderBy } from 'lodash-es';

const getCurrentGame = () => {
  if (browser) {
    const game = window.localStorage.getItem('currentGame');
    return game ? (JSON.parse(game) as G.Game) : undefined;
  }
};

const setCurrentGame = (game: G.Game) => {
  if (browser) {
    window.localStorage.setItem('currentGame', JSON.stringify(game));
  }
};

const getCurrentRound = () => {
  if (browser) {
    const currentGame = getCurrentGame();
    if (!currentGame) return;
    return currentGame.players[0].rounds.length + 1;
  }
};

const getCompletedRoundsCount = () => {
  if (browser) {
    const game = window.localStorage.getItem('currentGame') || '{}';
    const currentGame: G.Game = JSON.parse(game);
    return currentGame.players[0].rounds.length;
  }
};

type PlayerTotal = G.Player & {
  total: number | null;
  totalByRound: (number | null)[];
};

const getTotals = (): PlayerTotal[] => {
  if (browser) {
    const game = getCurrentGame();
    if (game?.players) {
      const totals = game.players.map((player) => {
        let total: null | number = null;
        let totalByRound: (number | null)[] = [];
        player.rounds.forEach((round) => {
          if (round || round === 0) {
            total = (total ?? 0) + round;
          }
          const prevTotal = totalByRound[totalByRound.length - 1];
          totalByRound.push(round !== null || prevTotal ? (prevTotal ?? 0) + (round ?? 0) : null);
        });
        return { ...player, total, totalByRound };
      });
      const playersWithNoScores = totals.filter((total) =>
        total.rounds.every((score) => score === null),
      );
      const playersWithAtLeastOneScore = totals.filter(
        (total) => !total.rounds.every((score) => score === null),
      );
      const orderedPlayersWithAtLeastOneScore = orderBy(
        playersWithAtLeastOneScore,
        ['total'],
        [game.sortOrder],
      );
      return [...orderedPlayersWithAtLeastOneScore, ...playersWithNoScores];
    }
  }
  return [];
};

const getPreferredView = () => {
  if (browser) {
    const currentGame = getCurrentGame();
    return currentGame?.preferredView;
  }
}

const setPreferredView = (view: string | undefined) => {
  if(browser){
    const currentGame = getCurrentGame();
    if (currentGame && ['table', 'chart'].includes(`${view}`)) {
      currentGame.preferredView = view as 'table' | 'chart';
      setCurrentGame(currentGame);
    }
  }
}

const getPlayers = () => {
  if (browser) {
    const currentGame = getCurrentGame();
    if (!currentGame) return;
    return currentGame.players.map((player) => player.name);
  }
};

const chartColors = [
  // Dark Colors
  '#C22D2D',
  '#304BB5',
  '#E5DB21',
  '#31A033',
  '#FA7F33',
  '#9340E5',
  '#33C7CC',
  '#F23BD1',
  '#88675A',
  '#529FF0',
  // Any excess of colors after this should be randomly generated by chroma.js
];

export {
  getCurrentGame,
  setCurrentGame,
  getCurrentRound,
  getCompletedRoundsCount,
  getTotals,
  getPreferredView,
  setPreferredView,
  getPlayers,
  chartColors,
};
