// generated by unplugin-svelte-components
// We suggest you to commit this file into source control
declare global {
    const GBtn: typeof import("nathanblaylock.com")["GBtn"]
    const GCheckbox: typeof import("nathanblaylock.com")["GCheckbox"]
    const GCheckboxGroup: typeof import("nathanblaylock.com")["GCheckboxGroup"]
    const GDebug: typeof import("nathanblaylock.com")["GDebug"]
    const GDevNote: typeof import("nathanblaylock.com")["GDevNote"]
    const GIcon: typeof import("nathanblaylock.com")["GIcon"]
    const GIconBtn: typeof import("nathanblaylock.com")["GIconBtn"]
    const GRadioGroup: typeof import("nathanblaylock.com")["GRadioGroup"]
    const GSegmentedControl: typeof import("nathanblaylock.com")["GSegmentedControl"]
    const GSortableCards: typeof import("nathanblaylock.com")["GSortableCards"]
    const GTextInput: typeof import("nathanblaylock.com")["GTextInput"]
}

export {}
