// generated by unplugin-svelte-components
// We suggest you to commit this file into source control
declare global {
    const GBtn: typeof import("nathanblaylock.com")["GBtn"]
    const GDebug: typeof import("nathanblaylock.com")["GDebug"]
    const GDevNote: typeof import("nathanblaylock.com")["GDevNote"]
    const GIcon: typeof import("nathanblaylock.com")["GIcon"]
    const GIconBtn: typeof import("nathanblaylock.com")["GIconBtn"]
}

export {}
